---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: tf-cloudflare-tunnel
  namespace: terraform
spec:
  path: ./../module
  workspace: terraform
  interval: 1m
  vars:
    - name: name
      value: k0s-cluster-prod-01
  varsFrom:
    - kind: Secret
      name: cloudflare-credentials
  sourceRef:
    kind: GitRepository
    name: tf-cloudflare-tunnel
    namespace: flux-system
